#!/bin/sh

if [ "$1" = "compose" ] && [ "$2" = "config" ]; then
  printf '%s\n' 'fake compose diagnostic: compose file is invalid' >&2
  exit 42
fi

printf '%s\n' 'fake docker received an unexpected command' >&2
exit 64
