- DLC 空间:
    - 主页:
        icon: mdi-home
        href: https://dailecheng.xyz/
        description: 个人主页
    - 博客:
        icon: mdi-notebook-outline
        href: https://blog.dailecheng.xyz/
        description: 记录技术实践与生活片段
    - 网盘:
        icon: mdi-folder-account-outline
        href: https://pan.dailecheng.xyz/
        description: 私有文件空间
    - 网址集:
        icon: mdi-compass-outline
        href: https://web.dailecheng.xyz/
        description: 常用网站与资源
    - 今日热榜:
        icon: mdi-fire
        href: https://hot.dailecheng.xyz/
        description: 聚合今日热点
    - 音乐站:
        icon: mdi-music
        href: https://audio.dailecheng.xyz/
        description: 聆听喜欢的音乐
